[buildpack]
name = "heroku-buildpack-ffmpeg-latest"
[buildpack-2]
name = "heroku-opus" 
[buildpack-2]
name = "Python"
[publish.Ignore]
files = [
  ".git",
  ".circleci/",
  ".github/",
  "builds/",
  "spec/",
  ".dockerignore",
  ".gitignore",
  ".rubocop.yml",
  "Gemfile",
  "Gemfile.lock",
  "hatchet.json",
  "hatchet.lock",
  "Makefile",
  "requirements.txt",
]